### ISSUE TITLE
Add remote containers support to all solutions.

### ISSUE THREAD

**Issue by PiotrJustyna** [PiotrJustyna/road-to-orleans#6]
- [ ] Overall GH Codespace support
- [x] Solution 1
- [x] Solution 2
- [x] Solution 3
- [x] Solution 3a
- [x] Solution 3b
- [x] Solution 4
- [x] Solution 4b
- [ ] Solution 5
- [ ] Solution 5a
- [ ] Solution 6
- [ ] Solution 7
- [ ] Solution 8

**Comment by PiotrJustyna** [comment]
Done in:

* Solution 1
* Solution 2

**Comment by askpt** [comment]
@PiotrJustyna what approach should I follow for this task? When we try to open a new GH codespace it requires the `.devcontainer` folder to be at the root of the repository, but before we are putting the folder in each solution. I can finish the rest of the Solutions that are missing.

**Comment by PiotrJustyna** [comment]
Let's maybe try to support both if possible? To cover all bases.
